In [1]:
import polars as pl
import src.curvas_financiacion as cfin

# Lee insumos
input_infl = pl.read_excel('./inputs/inflacion_mensual.xlsx')
df_ipc = cfin.procesar_inflacion(input_infl)
df_ipc

shape: (57, 3)
┌───────────┬───────────┬────────────┐
│ mesid_ipc ┆ tasa      ┆ indice_ipc │
│ ---       ┆ ---       ┆ ---        │
│ i32       ┆ f64       ┆ f64        │
╞═══════════╪═══════════╪════════════╡
│ 202104    ┆ 0.005923  ┆ 1.005923   │
│ 202105    ┆ 0.0099945 ┆ 1.015977   │
│ 202106    ┆ -0.000491 ┆ 1.015477   │
│ 202107    ┆ 0.0032499 ┆ 1.018778   │
│ 202108    ┆ 0.0044742 ┆ 1.023336   │
│ …         ┆ …         ┆ …          │
│ 202508    ┆ 0.0018768 ┆ 1.40953    │
│ 202509    ┆ 0.003196  ┆ 1.414035   │
│ 202510    ┆ 0.001842  ┆ 1.416639   │
│ 202511    ┆ 0.0007198 ┆ 1.417659   │
│ 202512    ┆ 0.0026681 ┆ 1.421441   │
└───────────┴───────────┴────────────┘

In [2]:
input_curvas = pl.read_excel('./inputs/irr_mensual_202411.xlsx')
input_curvas

shape: (3_960, 6)
┌──────┬──────┬─────────────┬────────┬─────────────┬──────────────┐
│ mes  ┆ pais ┆ consecutivo ┆ moneda ┆ fecha_clave ┆ tasa_interes │
│ ---  ┆ ---  ┆ ---         ┆ ---    ┆ ---         ┆ ---          │
│ i64  ┆ str  ┆ str         ┆ str    ┆ i64         ┆ f64          │
╞══════╪══════╪═════════════╪════════╪═════════════╪══════════════╡
│ 1    ┆ CO   ┆ CO_COP001M  ┆ COP    ┆ 20241130    ┆ 9.111264     │
│ 2    ┆ CO   ┆ CO_COP002M  ┆ COP    ┆ 20241130    ┆ 9.111264     │
│ 3    ┆ CO   ┆ CO_COP003M  ┆ COP    ┆ 20241130    ┆ 9.111264     │
│ 4    ┆ CO   ┆ CO_COP004M  ┆ COP    ┆ 20241130    ┆ 9.111264     │
│ 5    ┆ CO   ┆ CO_COP005M  ┆ COP    ┆ 20241130    ┆ 9.111264     │
│ …    ┆ …    ┆ …           ┆ …      ┆ …           ┆ …            │
│ 1316 ┆ CO   ┆ CO_USD1316M ┆ USD    ┆ 20241130    ┆ 5.2714       │
│ 1317 ┆ CO   ┆ CO_USD1317M ┆ USD    ┆ 20241130    ┆ 5.2714       │
│ 1318 ┆ CO   ┆ CO_USD1318M ┆ USD    ┆ 20241130    ┆ 5.2714       │
│ 1319 ┆ CO   ┆ CO_USD1319M ┆ USD    ┆ 20241130    ┆ 5.2714       │
│ 1320 ┆ CO   ┆ CO_USD1320M ┆ USD    ┆ 20241130    ┆ 5.2714       │
└──────┴──────┴─────────────┴────────┴─────────────┴──────────────┘

In [3]:
param_compfin = pl.read_excel('./inputs/insumos.xlsx', sheet_name='componente_financiacion')
param_compfin

shape: (2, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tipo_cont ┆ tipo_insu ┆ compania ┆ ramo_sura ┆ … ┆ aplica_ip ┆ pais_curv ┆ moneda_cu ┆ meses_max │
│ abilidad  ┆ mo        ┆ ---      ┆ ---       ┆   ┆ c_mensual ┆ a         ┆ rva       ┆ _vigencia │
│ ---       ┆ ---       ┆ str      ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆          ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ i64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ifrs17_lo ┆ *         ┆ 01       ┆ 003       ┆ … ┆ 1         ┆ CO        ┆ UVR       ┆ 120       │
│ cal       ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ ifrs17_co ┆ *         ┆ 01       ┆ 003       ┆ … ┆ 1         ┆ CO        ┆ UVR       ┆ 120       │
│ rporativo ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
# Procesa las curvas para derivar factores financieros
df_factores_interes = cfin.procesar_curvas_tasas(input_curvas, param_compfin)
df_factores_interes

shape: (122, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ mesid_cur ┆ fecha_cur ┆ moneda_cu ┆ pais_curv ┆ … ┆ tasa_fwd_ ┆ factor_ac ┆ factor_de ┆ sum_desc │
│ va        ┆ va        ┆ rva       ┆ a         ┆   ┆ real      ┆ umulacion ┆ sc_real   ┆ _real    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i32       ┆ date      ┆ str       ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.00288   ┆ 1.00288   ┆ 0.997128  ┆ 0.997128 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.00288   ┆ 1.005768  ┆ 0.994265  ┆ 1.991393 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.00288   ┆ 1.008665  ┆ 0.991409  ┆ 2.982802 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.00288   ┆ 1.01157   ┆ 0.988562  ┆ 3.971365 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.00288   ┆ 1.014483  ┆ 0.985723  ┆ 4.957088 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.004138  ┆ 1.651734  ┆ 0.605425  ┆ 92.97975 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.004132  ┆ 1.658559  ┆ 0.602933  ┆ 93.58269 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.004134  ┆ 1.665415  ┆ 0.600451  ┆ 94.18314 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.004137  ┆ 1.672305  ┆ 0.597977  ┆ 94.78112 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 202411    ┆ 2024-11-3 ┆ UVR       ┆ CO        ┆ … ┆ 0.004135  ┆ 1.67922   ┆ 0.595514  ┆ 95.37663 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Prueba Pipeline

In [5]:
import src.parametros as p
import src.aux_tools as aux_tools
import src.prep_insumo as prep_data
import src.devenga as devg
import src.fluctuacion as fluc
import src.mapeo_contable as mapcont
import polars as pl


# lee los parámetros e insumos relevantes
FECHA_VALORACION = p.FECHA_VALORACION
FECHA_VALORACION_ANTERIOR = p.FECHA_VALORACION_ANTERIOR
FECHA_TRANSICION = p.FECHA_TRANSICION
# Insumos transversales
param_contab = pl.read_excel(
    p.RUTA_INSUMOS, sheet_name=p.HOJA_PARAMETROS_CONTAB
).filter(pl.col("estado_insumo") == 1)  # Solo se usan las configuraciones activas (1)
excepciones = pl.read_excel(p.RUTA_INSUMOS, sheet_name=p.HOJA_EXCEPCIONES_50_50)
gasto = pl.read_excel(p.RUTA_GASTOS)
tasa_cambio = pl.read_excel(p.RUTA_INSUMOS, sheet_name=p.HOJA_MONEDA)
descuentos = pl.read_excel(p.RUTA_INSUMOS, sheet_name=p.HOJA_DESCUENTO)
# El diccionario o tabla de correspondencia de outputs con entradas contables
input_map_bts = pl.read_excel(p.RUTA_REL_BT)
input_tipo_seguro = pl.read_excel(p.RUTA_INSUMOS, sheet_name=p.HOJA_TIPO_SEGURO)
# Insumos de cuenta corriente y cartera
# input_cuentas_reaseguro = pl.read_excel(p.RUTA_INSUMOS, sheet_name=p.HOJA_CUENTAS_REA)
# Insumo de riesgo de credito reaseguradores
input_riesgo_credito = pl.read_excel(p.RUTA_RIESGO_CREDITO)

# Insumos de recibos contabilizados en SAP
produccion_dir = pl.read_excel(p.RUTA_INSUMOS, sheet_name=p.HOJA_PDN)
cesion_rea = pl.read_excel(p.RUTA_INSUMOS, sheet_name=p.HOJA_CESION)

# prepara el insumo para el devengo de produccion directo
input_prod_dir = prep_data.prep_input_prima_directo(
    produccion_dir, param_contab, excepciones, FECHA_VALORACION
)
input_prod_dir

Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 16, falling back to string

shape: (67, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ aux_casui ┆ tipo_insu ┆ tipo_nego ┆ poliza    ┆ … ┆ fecha_con ┆ fecha_ini ┆ fecha_fin ┆ valor_ba │
│ stica     ┆ mo        ┆ cio       ┆ ---       ┆   ┆ stitucion ┆ cio_deven ┆ _devengo  ┆ se_deven │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ go        ┆ ---       ┆ go       │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ date      ┆ ---       ┆ date      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ date      ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ garantia_ ┆ produccio ┆ directo   ┆ 259823906 ┆ … ┆ 2023-07-1 ┆ 2023-07-1 ┆ 2025-01-1 ┆ 1200.0   │
│ extendida ┆ n_directo ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆          │
│ _pre_ries ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ go        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ garantia_ ┆ produccio ┆ directo   ┆ 259823906 ┆ … ┆ 2023-07-1 ┆ 2023-07-1 ┆ 2025-01-1 ┆ 1200.0   │
│ extendida ┆ n_directo ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆          │
│ _pre_ries ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ go        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ garantia_ ┆ produccio ┆ directo   ┆ 259823906 ┆ … ┆ 2023-07-1 ┆ 2023-07-1 ┆ 2025-01-1 ┆ 1200.0   │
│ extendida ┆ n_directo ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆          │
│ _pre_ries ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ go        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ garantia_ ┆ produccio ┆ directo   ┆ 920350354 ┆ … ┆ 2024-07-0 ┆ 2024-07-0 ┆ 2025-01-1 ┆ 1200.0   │
│ extendida ┆ n_directo ┆           ┆           ┆   ┆ 1         ┆ 1         ┆ 5         ┆          │
│ _en_riesg ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ o         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ garantia_ ┆ produccio ┆ directo   ┆ 920350354 ┆ … ┆ 2024-07-0 ┆ 2024-07-0 ┆ 2025-01-1 ┆ 1200.0   │
│ extendida ┆ n_directo ┆           ┆           ┆   ┆ 1         ┆ 1         ┆ 5         ┆          │
│ _en_riesg ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ o         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ decenal_f ┆ produccio ┆ directo   ┆ 003000000 ┆ … ┆ 2024-12-1 ┆ 2024-12-1 ┆ 2034-12-1 ┆ 3.154561 │
│ inanciaci ┆ n_directo ┆           ┆ 545       ┆   ┆ 5         ┆ 5         ┆ 5         ┆ 9e8      │
│ on        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ matematic ┆ matematic ┆ directo   ┆ 190358223 ┆ … ┆ 2024-01-3 ┆ 2024-01-3 ┆ null      ┆ 1200.0   │
│ a_local_d ┆ a_local_d ┆           ┆           ┆   ┆ 0         ┆ 0         ┆           ┆          │
│ irecto    ┆ irecto    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mensual_p ┆ produccio ┆ directo   ┆ 634535346 ┆ … ┆ 2023-12-1 ┆ 2024-01-1 ┆ 2024-02-1 ┆ 100.0    │
│ re_vigenc ┆ n_directo ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆          │
│ ia        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mensual_p ┆ produccio ┆ directo   ┆ 634535346 ┆ … ┆ 2023-12-1 ┆ 2024-01-1 ┆ 2024-02-1 ┆ 100.0    │
│ re_vigenc ┆ n_directo ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆          │
│ ia        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mensual_p ┆ produccio ┆ directo   ┆ 634535346 ┆ … ┆ 2023-12-1 ┆ 2024-01-1 ┆ 2024-02-1 ┆ 100.0    │
│ re_vigenc ┆ n_directo ┆           ┆           ┆   ┆ 5         ┆ 5         ┆ 5         ┆          │
│ ia        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
# Se añade el paso de anexar info financiacion
input_pdn_final = prep_data.anexar_info_financiacion(
    input_prod_dir,
    param_compfin,
    df_ipc,
    df_factores_interes,
    FECHA_VALORACION    
)
input_pdn_final.filter(pl.col('aplica_comp_financ') == 1)

shape: (2, 63)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ aux_casui ┆ tipo_insu ┆ tipo_nego ┆ poliza    ┆ … ┆ desc_lir_ ┆ fact_acum ┆ sum_desc_ ┆ desc_lir │
│ stica     ┆ mo        ┆ cio       ┆ ---       ┆   ┆ nodo_ini  ┆ _ini      ┆ lir_nodo_ ┆ _nodo_fi │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ fin       ┆ n        │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ decenal_f ┆ produccio ┆ directo   ┆ 003000000 ┆ … ┆ 0.997128  ┆ 1.00288   ┆ 94.78112  ┆ 0.597977 │
│ inanciaci ┆ n_directo ┆           ┆ 545       ┆   ┆           ┆           ┆           ┆          │
│ on        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ decenal_f ┆ produccio ┆ directo   ┆ 003000000 ┆ … ┆ 0.997128  ┆ 1.00288   ┆ 94.78112  ┆ 0.597977 │
│ inanciaci ┆ n_directo ┆           ┆ 545       ┆   ┆           ┆           ┆           ┆          │
│ on        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
out_cf_test = devg.devengar(input_pdn_final.filter(pl.col('aplica_comp_financ') == 1),
                            FECHA_VALORACION)
out_cf_test.write_clipboard()
out_cf_test

shape: (2, 92)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ aux_casui ┆ tipo_insu ┆ tipo_nego ┆ poliza    ┆ … ┆ valor_con ┆ valor_lib ┆ valor_lib ┆ saldo    │
│ stica     ┆ mo        ┆ cio       ┆ ---       ┆   ┆ stitucion ┆ eracion   ┆ eracion_a ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ cum       ┆ f64      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ decenal_f ┆ produccio ┆ directo   ┆ 003000000 ┆ … ┆ -0.0      ┆ 3.5121e6  ┆ null      ┆ -3.0590e │
│ inanciaci ┆ n_directo ┆           ┆ 545       ┆   ┆           ┆           ┆           ┆ 8        │
│ on        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ decenal_f ┆ produccio ┆ directo   ┆ 003000000 ┆ … ┆ -0.0      ┆ 3.5121e6  ┆ null      ┆ -3.0590e │
│ inanciaci ┆ n_directo ┆           ┆ 545       ┆   ┆           ┆           ┆           ┆ 8        │
│ on        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘